name: baseline-rsnn

dropout_p: 0.3

tau_mem: 20e-3
tau_syn: 10e-3

het_timescales: True
het_timescales_readout: True

learn_timescales: True
learn_timescales_readout: True

delta_synapses: False

nb_hidden: 1
hidden_size: [64]
recurrent: [True] 

multiple_readouts: False

tau_mem_readout: 50e-3
tau_syn_readout: 10e-3

is_half: True