defaults:
  - filenames: filenames
  - pretrain_filenames: all-filenames
  - _self_

data_dir: /home/cc/efficient-rsnn-bmi/data/datasets

dt: 4e-3  # Time step (seconds)

# train_ratio: 0.8  # Ratio of training set.
ratio_val: 0.1 # Ratio of validation set. 
random_val: False

nb_outputs: 2  # Number of outputs
nb_inputs:
  loco: 192
  indy: 96

stride: 4e-3
# stride: 0.2  
extend_data: True
sample_duration: 2.0

remove_segments_inactive: False  

# Data augmentation
p_drop: 0.0  # Probability of dropping a spike
p_insert: 0.0  # Probability of inserting a spike
jitter_sigma: 0.0  # Jitter sigma (in number of time steps)