filename: indy_20170131_02.mat
file_path: /home/cc/efficient-rsnn-bmi/data/datasets

train_ratio: 0.8  # Ratio of training set.
val_ratio: 0.1  # Ratio of validation set. 
random_val: False

stride: 0.004  # Time step of the data
extend_data: True
sample_duration: 2.0

remove_segments_inactive: False  

# Data augmentation
p_drop: 0.0  # Probability of dropping a spike
p_insert: 0.0  # Probability of inserting a spike
jitter_sigma: 0.0  # Jitter sigma (in number of time steps)