defaults:
  - _self_
  - datasets: data
  - experiments: baseline
  - evaluation: eval-default
  - override hydra/hydra_logging: disabled

dtype: 'float32'

# If pretraining is False, you can set the load_state to a path to load a pre-trained model for each monkey
# If state is not found, a model will be trained from scratch on each session
pretraining: True
load_state: 
  loco: False
  indy: False

train_monkey: indy # or loco

eval_data: indy_20170131_02.mat
# eval_data: indy_20160630_01.mat
# eval_data: indy_20160622_01.mat

eval_model: /home/cc/efficient-rsnn-bmi/pretrained_models/synaps-delay/synapse_delay.pth
# eval_model: /home/cc/efficient-rsnn-bmi/pretrained_models/baselines/baseline.pth
# eval_model: /home/cc/efficient-rsnn-bmi/pretrained_models/interpolations/2_keys_interpolation.pth
# eval_model: /home/cc/efficient-rsnn-bmi/pretrained_models/interpolations/8_keys_interpolation.pth
# eval_model: /home/cc/efficient-rsnn-bmi/pretrained_models/baselines/tet_baseline.pth
# eval_model: /home/cc/efficient-rsnn-bmi/pretrained_models/synaps-delay/tet_synaps_delay.pth

seed: 42 # change this later

hydra:
  output_subdir: null
  run:
    dir: .
