defaults:
  - _self_
  - datasets: data
  - training: training
  - initializer: initializer
  - model: model
  - plotting: plotting
  - evaluation: eval-default
  - delay: delay

model_name: "rsnn_optimized"
experiment: "neurobench"

dtype: 'float32'
# node: False # this is the deprecated one
device: "cuda"
nb_workers: 2

pretraining: True

# If pretraining is False, you can set the load_state to a path to load a pre-trained model for each monkey
# If state is not found, a model will be trained from scratch on each session
load_state: 
  loco: "efficient-rsnn-bmi/outputs/baseline/2025-05-19_12-37-22/baselineRSNN-results-pretraining-loco.json"
  indy: "efficient-rsnn-bmi/outputs/baseline/2025-05-19_12-37-22/baselineRSNN-results-pretraining-indy.pth"
train_monkeys:
  - indy
  - loco

seed: True