defaults:
  - defaults
  - model/model@baselineRSNN
  - training/training@baselineRSNNtraining
  - _self_

device: "cpu"
dtype: 'float32'


output_dir : ./output
model_dir: ./models

modelname: 'baselineRSNN'    # 'tinyRSNN' or 'bigRSNN' or 'all'

use_snnTorch_model: False   # Set to True to use the equivalent snnTorch model instead of `stork` model for evaluation

# Benchmarking
static_metrics:
  - footprint
  - connection_sparsity

workload_metrics:
  - r2
  - activation_sparsity
  - synaptic_operations